# Generated by Django 4.0.4 on 2022-06-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='tienda/sinimagen.png', upload_to='tienda/'),
        ),
    ]
